### ISSUE TITLE
Correção Exercício `0.5.1`

### ISSUE THREAD

**Issue by mathiasgheno** [Bassetti97/Minhas-tarefas-exercicio#1]
# Correção Exercício `0.5.1`

> Considere o wireframe abaixo como um guia visual para um sistema web que faz listagem de tarefas considerando três status: Pendentes, Concluídas e Excluídas.  [Referência visual](https://i.imgur.com/AsfPVcN.jpg). 

Tudo ok.

**Nota:** 9

## Comentários

https://github.com/Bassetti97/EXERCICIO.EDITADO-0.5.1/blob/b8a37e8e94495f75009a32887576adea058e4693/0.5.1/stylo.css#L34-L54

Muito dos seus estilos em `.pendentes`, `.concluidas` e `.excluidas` estão duplicadas. Você pode reduzir essa duplicidade com a criação de uma classe comum. Veja o exemplo abaixo. 

```css

a.menu {
   color: var(--cor-letra); 
    font-family: sans-serif;
    text-decoration: none; 
    font-weight: bold;
}

a.pendentes {
    background-color: var(--cor-pendentes);
}
```

No HTML basta fazer uso das duas classes. 

```html
<nav>
    <ul>
        <a class="menu pendentes" href="pendentes.html">Pendentes</a>
    </ul>
</nav>
```

[^1]: [Caminhos: entenda as diferenças entre absolutos e relativos](https://www.alura.com.br/artigos/caminhos-entenda-diferencas-entre-absolutos-relativos?gclid=CjwKCAjw9J2iBhBPEiwAErwpeZOH615fG9QWBpSN2UuIKVbpf6WWD9sknST-4DwVDHzcCBBuMOYuzhoCbNsQAvD_BwE)
[^2]: [CSS Selectors ─ Element Element Selector](https://www.w3schools.com/cssref/sel_element_element.php)
[^3]: [CSS Variables ─ An Introduction](https://youtu.be/PHO6TBq_auI)
[^4]: [HTML Lists](https://www.w3schools.com/html/html_lists.asp)
